name: Rain Alert

on:
  schedule:
    # Runs every day at 13:00 UTC (9:00 AM in Toronto during EDT)
    - cron: "0 13 * * *"

  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    env:
      OWM_API_KEY: ${{ secrets.OWM_API_KEY }}
      ACCOUNT_SID: ${{ secrets.ACCOUNT_SID }}
      AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
      MY_LAT: ${{ secrets.MY_LAT }}
      MY_LNG: ${{ secrets.MY_LNG }}
      V_SIM: ${{ secrets.V_SIM }}
      MY_SIM: ${{ secrets.MY_SIM }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Rain Alert
        run: python main.py
